require 'kickstart.plugins.guess-indent'
require 'kickstart.plugins.web-devicons'
require 'kickstart.plugins.gitsigns'
require 'kickstart.plugins.which-key'
require 'kickstart.plugins.todo-comments'
require 'kickstart.plugins.mini'
require 'kickstart.plugins.telescope'
require 'kickstart.plugins.fidget'
require 'kickstart.plugins.lsp'
require 'kickstart.plugins.conform'
require 'kickstart.plugins.luasnip'
require 'kickstart.plugins.blink-cmp'
require 'kickstart.plugins.treesitter'

-- Optional plugins (uncomment to enable):
-- require 'kickstart.plugins.debug'
-- require 'kickstart.plugins.indent_line'
-- require 'kickstart.plugins.lint'
-- require 'kickstart.plugins.autopairs'
-- require 'kickstart.plugins.neo-tree'
-- require 'kickstart.plugins.gitsigns-keymaps'
