#!/usr/bin/env bash

set -e

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
cyan="\033[0;36m"
nocolor="\033[0m"

files="\
  bash_aliases \
  bash_profile \
  bashrc \
  config \
  gemrc \
  gitconfig \
  gitignore \
  inputrc \
  phoenix.js \
  ptconfig.toml \
  tmux.conf \
  tmuxstatusline.conf \
  vim \
  vimrc \
  "

for file in $files; do
  source="$(pwd)/$file"
  target="$HOME/.$file"

  echo -en "~/.${file} ... "

  if [ ! -e "$source" ]; then
    echo -e "${red}${file} doesn't exist${nocolor}"

  elif [ -h "$target" ]; then
    echo -e "${green}installed${nocolor}"

  elif [ -d "$target" ] || [ -f "$target" ]; then
    echo -e "${red}something already exists here${nocolor}"

  else
    ln -s "$source" "$target"

    echo -e "${yellow}link created${nocolor}"
  fi
done
